// Generated by CoffeeScript 1.9.3
var CONFIG_DIR, args, configName, fs, path;

fs = require('fs');

CONFIG_DIR = process.env.HOME + "/.mehserve";

args = process.argv.slice(2);

if (args[0] === "install") {
  console.log("Run:\n\n  sudo cp " + __dirname + "/meh.resolver /etc/resolver/meh\n  sudo cp " + __dirname + "/meh.resolver /etc/resolver/dev\n  sudo cp " + __dirname + "/meh.firewall.plist /Library/LaunchDaemons/meh.firewall.plist\n  sudo launchctl load -w /Library/LaunchDaemons/meh.firewall.plist");
} else if (args[0] === "run") {
  require('./index');
} else if (args.length === 2) {
  configName = args[0];
  path = CONFIG_DIR + "/" + configName;
  fs.writeFileSync(path, args[1]);
} else {
  console.log("Usage:\n\n  mehserve install\n  mehserve run\n  mehserve [subdomain] [destination]\n\nDestination can be a path or a port number.");
}

//# sourceMappingURL=cli.js.map
