// Generated by CoffeeScript 1.9.2
var CONFIG_DIR, args, configName, fs, path;

fs = require('fs');

CONFIG_DIR = process.env.HOME + "/.mehserve";

args = process.argv.slice(2);

if (args.length === 2) {
  configName = args[0];
  path = CONFIG_DIR + "/" + configName;
  fs.writeFileSync(path, args[1]);
} else {
  console.log("Usage: mehserve [subdomain] [destination]\n\nDestination can be a path or a port number.");
}

//# sourceMappingURL=cli.js.map
